name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@wuiyang'

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build and publish package on NPM 📦
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@users.noreply.github.com"
          npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOGEN_TOKENS_GITHUB: ${{ secrets.GITHUB_TOKEN }}
